name: Docker Image CI

on:
  push:
    paths:
      - '!*.md'
      - '!LICENSE'
    tags:
      -'**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/serv:${{ github.ref_name }} .

      # Step 3.1: Build the Docker image for latest
      - name: Build Docker for latest Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/serv:latest .

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/serv:${{ github.ref_name }}
          
      # Step 4.1: Push the Docker latest image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/serv:latest
